### PR TITLE
Concerning `Field.get_coordinate_reference`

### LINKED ISSUE #236: `Field.get_coordinate_reference` errors on bad kwarg
As-is, with the present cf-python and cfdm `master` branches, `Field.get_coordinate_reference` will always error due to an upstream `TypeError` from an invalid keyword argument in `cfdm`, which ultimately looks like it is case of a missed API conversion in `cfdm` of https://github.com/NCAS-CMS/cfdm/issues/132:

```pycon
>>> import cf
>>> f = cf.example_field(1)
>>> f.get_coordinate_reference()
Traceback (most recent call last):
  File "/home/sadie/cfdm/cfdm/constructs.py", line 1402, in filter
    filter_method = getattr(self, "_" + method)
AttributeError: 'Constructs' object has no attribute '_identity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sadie/cf-python/cf/mixin/fielddomain.py", line 2283, in get_coordinate_reference
    return self.coordinate_reference(
  File "/home/sadie/cf-python/cf/mixin/fielddomain.py", line 1819, in coordinate_reference
    return self._construct(
  File "/home/sadie/cf-python/cf/mixin/fielddomain.py", line 162, in _construct
    c = getattr(self, _constructs_method)(*identities, **filter_kwargs)
  File "/home/sadie/cfdm/cfdm/mixin/fielddomain.py", line 547, in coordinate_references
    return self._filter_interface(
  File "/home/sadie/cfdm/cfdm/mixin/fielddomain.py", line 278, in _filter_interface
    c = self.constructs.filter(
  File "/home/sadie/cfdm/cfdm/constructs.py", line 1404, in filter
    raise TypeError(
TypeError: Constructs.filter() has an unexpected keyword argument 'identity'
```

#### Fix

This should be an easy fix, so I will self-assign and put in a PR shortly.

#### Env

As observed with:
```pycon
>>> cf.environment(paths=False)
Platform: Linux-4.15.0-54-generic-x86_64-with-glibc2.10
HDF5 library: 1.10.6
netcdf library: 4.8.0
udunits2 library: /home/sadie/anaconda3/envs/cf-env/lib/libudunits2.so.0
Python: 3.8.10
netCDF4: 1.5.6
cftime: 1.5.0
numpy: 1.20.3
psutil: 5.8.0
scipy: 1.6.3
matplotlib: 3.4.2
ESMF: 8.1.1
cfdm: 1.8.9.0
cfunits: 3.3.3
cfplot: 3.1.5
cf: 3.10.0
```

and using the (at time of posting) current `master` branches for both `cf` and `cfdm`.

### PR DESCRIPTION
**Pull request by sadielbartholomew**
To close #236 and (if we want to keep it as a method, see suggestion below), in the process improve the testing and documentation of `Field.get_coordinate_reference`.

I have made the basic update to apply the construct access API change that was missed for v3.10.0 via cfdm v1.8.9.0, in 32a8787, but this PR remains a draft because I also want to flash out the corresponding API documentation but:
* I am [also unsure](https://github.com/NCAS-CMS/cf-python/issues/236#issuecomment-881358028) of the intended role of the `construct` keyword.
 * It is not entirely clear to me from the code (given the lack of summary line in the docstring/docs) the intention of the method `Field.get_coordinate_reference`, in particular how it differs to `cf.Field.coordinate_reference` (from `cf`) and `cf.Field.coordinate_references` (from `cfdm`), because obviously it isn't a straightforward alias to either of those.

@davidhassell would you mind clarifying? If there isn't a specific difference to make this method worthwhile, could we just make it an alias to `coordinate_reference`? Also, unless you can recall or detect some clear purpose for the `construct` parameter, I suggest we just drop it from the method. In any case, I am happy to scrap the PR as-is especially as there are few changes in the PR change set as it stands.

### CODE REVIEW

**Comment by sadielbartholomew** [comment]
There was a one-line mistake left in from development work, I have just pushed a fix. Opening and closing to retrigger the CI jobs which should now pass...

**Comment by sadielbartholomew** [comment]
The Actions CI is happy enough, apart from some hanging tests which have led the corresponding jobs to  which I am aware of from other PRs.

Just waiting now to discuss with David whether the approach is OK (i.e. review) and what the purpose of the method actually is so we can update the documentation, else change the method to be a direct alias and possibly deprecate...

**Review by davidhassell — APPROVED** [review]
Sorry it took a while for me to look at this - looks fine to me (I haven't run the new test, but it reads sensibly - I'm sure you have and it passes)

**Comment by sadielbartholomew** [comment]
Thanks for the review, @davidhassell. Since this is otherwise ready bar the documentation, I'll bump the documentation aspect to a separate issue and merge.

**Pull request merged**
