### PR TITLE
Correct finding coordrefs in `cf.aggregate`

### PR DESCRIPTION
**Pull request by davidhassell**
A bit tricky to test, as I can't see a case where the bug isn't benign: If two fields have different coordinate references, then they won't  get aggregated anyway, regardless of whether or not any coordinate references are attached to dimension coordinates (which is the "bug")

### CODE REVIEW

**Comment by sadielbartholomew** [comment]
Hi David, were you wanting a review on this - not sure since it's open not as a draft and seems ready but I've not been assigned, so thought I'd check?

**Review by sadielbartholomew — APPROVED** [review]
All good, though we might want to add a change log entry?

**Comment by davidhassell** [comment]
Got any ideas of what it could say (I haven't :))

**Comment by sadielbartholomew** [comment]
> Got any ideas of what it could say (I haven't :))

You make a good point, I do not :laughing: Therefore, leaving this out from the changelog only makes sense - as you imply, the bug this fixes could only manifest for users if they are doing something really quite strange, so is unlikely.

So, all good - please merge.

**Pull request merged**
