### PR TITLE
dask: `Data memory/disk`

### PR DESCRIPTION
**Pull request by davidhassell**

### CODE REVIEW

**Review by sadielbartholomew — COMMENTED** [review]
Perhaps I am missing something here, but the deprecation doesn't seem to be manifesting for `in_memory`, though it is working absolutely fine for the other methods and properties deprecated here, as indicated for one example below (and I have double checked the install of this `branch` is OK to be sure)? E.g:

```pytb
>>> d.to_disk()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sadie/cf-python/cf/data/mixin/deprecations.py", line 436, in to_disk
    _DEPRECATION_ERROR_METHOD(
  File "/home/sadie/cf-python/cf/functions.py", line 3197, in _DEPRECATION_ERROR_METHOD
    raise DeprecationError(
cf.functions.DeprecationError: Data method 'to_disk' has been deprecated at version TODODASK and is no longer available and will be removed at version 5.0.0. 
>>>
>>> d.to_memory()
Traceback (most recent call last):
  File "/home/sadie/cfdm/cfdm/core/abstract/container.py", line 262, in _get_component
    return self._components[component]
KeyError: 'array'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sadie/cfdm/cfdm/decorators.py", line 44, in inplace_wrapper
    processed_copy = operation_method(self, *args, **kwargs)
  File "/home/sadie/cfdm/cfdm/data/data.py", line 2700, in to_memory
    d._set_Array(self.source().to_memory())
  File "/home/sadie/cfdm/cfdm/core/data/data.py", line 909, in source
    return self._get_component("array", default=default)
  File "/home/sadie/cfdm/cfdm/core/abstract/container.py", line 267, in _get_component
    return self._default(
  File "/home/sadie/cfdm/cfdm/core/abstract/container.py", line 144, in _default
    raise default
ValueError: Data has no 'array' component
```

**Comment by davidhassell** [comment]
Hi Sadie - look like the deprecation error wasn't working for any attributes . https://github.com/NCAS-CMS/cf-python/pull/387/commits/99cffd46d369a8df0cbcdd155650541b5eb1e1d4 should fix this: 
```python
>>> cf.Data(9).in_memory
Traceback
    ...
DeprecationError: Data attribute 'in_memory' has been deprecated at version TODODASK and will be removed at version 5.0.0. 
```

**Comment by sadielbartholomew** [comment]
> look like the deprecation error wasn't working for any attributes . https://github.com/NCAS-CMS/cf-python/commit/99cffd46d369a8df0cbcdd155650541b5eb1e1d4 should fix this

Nice, and it indeed does. What about `to_memory` though (as opposed to `in_`)? I think that's still not playing ball.

**Comment by davidhassell** [comment]
> What about to_memory though (as opposed to in_)? I think that's still not playing ball.

Ah. I see that that's inherited from `cfdm`. How about https://github.com/NCAS-CMS/cf-python/pull/387/commits/48e20fa12a2de01c9002b0d12d74e5ec893ced15?

**Comment by sadielbartholomew** [comment]
> Ah. I see that that's inherited from cfdm.

I raised it since you have added such a method to `cf/data/mixin/deprecations.py`, which had me a little confused. Not sure if that can just be removed now?

**Comment by davidhassell** [comment]
> I raised it since you have added such a method to cf/data/mixin/deprecations.py

Doh! https://github.com/NCAS-CMS/cf-python/pull/387/commits/7aecaca9ccd3c1a36814c2d0169b46069cd689cf

**Review by sadielbartholomew — APPROVED** [review]
This fell off my radar after my latest feedback comment, apologies. Your new commit is fine, so all good to merge! Thanks.

**Pull request merged**
