### PR TITLE
Fix for cf.aggregate failure when a datum or coordinate conversion parameter has an array value

### PR DESCRIPTION
**Pull request by davidhassell**
Fixes: #230

### CODE REVIEW

**Review by sadielbartholomew — COMMENTED** [review]
This seems to work well though:

* we could do with a corresponding test, ideally bundled with this PR, to isolate the original aggregate failure (as also indicated by the decrease in coverage on the Codecov report);
* given that the solution relies on the recursive function `_totuple`, I wonder if there may be a negative effect on performance (it's difficult to check that without a test to expose the case at hand, though) do you have any ideas about the potential hit in speed and/or the specifics and nicheness of the case that might influence how consequential it could be to users?

**Comment by davidhassell** [comment]
Thanks, Sadie.

I'm not too worried about performance. The recursive nature is "belt and braces" - there is no use case for multidimensional parameter values and none are specified by the conventions - so it shouldn't be a an issue. If it becomes so we can review it then.

Always a good idea to add a test! I'll do that ...

**Comment by sadielbartholomew** [comment]
> The recursive nature is "belt and braces" - there is no use case for multidimensional parameter values and none are specified by the conventions - so it shouldn't be a an issue. If it becomes so we can review it then.

Fair enough, that's all good by me.

> Always a good idea to add a test! I'll do that ...

Excellent, thanks. Please merge away once the test is complete (or tag me to look at the update if you prefer, I am happy to do so).

**Comment by davidhassell** [comment]
Test added, Pretty straight forward, so merging.

**Pull request merged**
